# Generated by Django 3.1.1 on 2023-01-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
